Update aflred version using git tag
mperezi/build-alfred-workflow pull request #4
Opened 2022-12-30 18:19 UTC by com30n

While using the workflow I found out that an alfred workflow version is not the same as tag in github release.
So, the changes I made can help to fix this :)

2023-01-02 10:59 UTC, almibarss commented
Thanks for contributing to this repo @com30n!
I like your idea of being able to customize the version of the output workflow file with the git tag (or any string actually). I've got a couple of suggestions though:
* Since the new version can be really anything and not just a git tag I'd change the name of the parameter from `tag_name` to `custom_version` to reflect that
* The custom version can go inside the `info.plist` as is but it needs to be sanitized to be part of the filename since it is provided by the user
* I would update the version with the custom version even if no version key is found inside the `info.plist` file

2023-01-02 12:17 UTC, com30n commented
Thank you for the answer @almibarss!

Yeah, I agree with you it would be very helpful.

> The custom version can go inside the info.plist as is but it needs to be sanitized to be part of the filename since it is provided by the user

How do you think, which naming conversation we can use here?
Something like that `^\S{,15}`?

2023-01-02 12:32 UTC, com30n commented
Updated the PR

2023-01-02 15:22 UTC, almibarss requested changes

2023-01-02 15:22 UTC, almibarss commented on extract_name.py
>          workflow_file += '-{}'.format(info['version'])
Actually you don't need to extract the tag name as `github.ref_name` already contains the information that you want as opposed to `github.ref`:

<img width="727" alt="image" src="https://user-images.githubusercontent.com/43891734/210250547-a9930699-79e1-4352-a1c1-dd1452bdf625.png">

https://docs.github.com/en/actions/learn-github-actions/contexts

```suggestion

    custom_version = os.environ.get("CUSTOM_VERSION")
    if custom_version:
        info['version'] = custom_version
        plistlib.writePlist(info, info_plist)

    if 'version' in info:
        workflow_file += '-{}'.format(safename(info['version']))
```

2023-01-03 12:45 UTC, almibarss requested changes

2023-01-03 12:45 UTC, almibarss commented on README.md
> +* `custom_version`: Custom version of your alfred workflow (like git tag name). It will sanitize the version using the regexp `^\S{,15}`. It updates the workflow version (it updates `info.plist` vers
```suggestion
* `custom_version`: String that will override the workflow version (a git tag name for example).
```

2023-01-03 12:45 UTC, almibarss commented on action.yml
> +    description: 'The name of the tag. This should come from the webhook payload, `github.GITHUB_REF` when a user pushes a new tag'
```suggestion
    description: 'String that will override the workflow version'
```

2023-01-03 13:05 UTC, com30n commented
Great, thank you @almibarss  for the fixes!

2023-01-03 13:09 UTC, merged

2023-01-03 13:09 UTC, almibarss commented
lgtm 👍🏾 Thank you @com30n